CREATE TABLE IF NOT EXISTS admin
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL ,
    password VARCHAR(255) NOT NULL
);

INSERT INTO admin(email, password)
VALUES
    ('admin@eurder.com', 'admin');

