CREATE TABLE IF NOT EXISTS item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(255) NOT NULL,
    price         DOUBLE PRECISION NOT NULL,
    stock_amount INT DEFAULT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS eurder
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_customer BIGINT DEFAULT NULL,
    CONSTRAINT id_customer FOREIGN KEY (id_customer) REFERENCES customer(id),
    eurder_date DATE NOT NULL,
    total_price  DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_eurder PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS item_group
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    item_price  DOUBLE PRECISION NOT NULL,
    amount INT DEFAULT NULL,
    shipping_date DATE NOT NULL,
    id_item BIGINT DEFAULT NULL,
    CONSTRAINT id_item FOREIGN KEY (id_item) REFERENCES item(id),
    id_eurder BIGINT DEFAULT NULL,
    CONSTRAINT id_eurder FOREIGN KEY (id_eurder) REFERENCES eurder(id)
);
